// Lucide-iconen geherexporteerd onder semantische namen — match material-symbols namen uit HTML.
export {
  LayoutGrid as Apps,
  TriangleAlert as AlertTriangle,
  ClipboardList,
  Flame,
  UserCog,
  FilterX,
  ExternalLink,
  Shield,
  Info,
  X,
  Ban,
  Bot,
  Settings2,
  Puzzle,
  Lock,
  Gavel,
  Flag,
  BadgeCheck,
  ScatterChart,
  Radar,
  Bolt,
  AlertCircle,
} from "lucide-react";
