INSERT INTO public.model_typekaarten (
  id, canonical_id, display_name, provider, model_type,
  gpai_designated, systemic_risk, eu_license_status,
  hosting_region, data_storage_region, trains_on_input,
  dpa_available, typekaart_version, status, last_verified_at,
  statutory_prohibitions, contractual_restrictions
) VALUES
('b1000000-0000-0000-0000-000000000001', 'chatgpt-plus', 'ChatGPT (Plus/Pro)', 'OpenAI', 'GPAI_LLM', true, true, 'open', 'US', 'US', false, true, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "Geen gebruik voor verboden doeleinden art. 5 EU AI Act", "source": "OpenAI Usage Policies"}]'::jsonb),
('b1000000-0000-0000-0000-000000000002', 'chatgpt-enterprise-eu', 'ChatGPT Enterprise (EU-hosted)', 'OpenAI / Microsoft Azure', 'GPAI_LLM', true, true, 'open', 'EU', 'EU', false, true, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "Vereist enterprise-overeenkomst met Microsoft Azure EU Data Boundary", "source": "Microsoft Azure EU Data Boundary"}]'::jsonb),
('b1000000-0000-0000-0000-000000000003', 'claude-ai-pro', 'Claude (Pro/Team)', 'Anthropic', 'GPAI_LLM', true, false, 'open', 'US', 'US', false, true, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "Geen gebruik voor massasurveillance, autonomous weapons, of andere verboden categorieën", "source": "Anthropic Usage Policy"}]'::jsonb),
('b1000000-0000-0000-0000-000000000004', 'microsoft-copilot-m365', 'Microsoft 365 Copilot', 'Microsoft', 'GPAI_LLM', true, true, 'open', 'EU', 'EU', false, true, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "Vereist M365 E3/E5 licentie + Copilot add-on", "source": "Microsoft Licensing"}, {"restriction": "Gegevensverwerking onder EU Data Boundary — controleer regioinstelling", "source": "Microsoft EU Data Boundary"}]'::jsonb),
('b1000000-0000-0000-0000-000000000005', 'google-gemini-workspace', 'Google Gemini (Workspace)', 'Google', 'GPAI_LLM', true, true, 'open', 'EU/US', 'EU/US', false, true, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "Datalocatie afhankelijk van Workspace-regio-instelling — controleer bij Workspace-beheerder", "source": "Google Workspace Admin"}]'::jsonb),
('b1000000-0000-0000-0000-000000000006', 'github-copilot-business', 'GitHub Copilot (Business)', 'Microsoft / GitHub', 'GPAI_CODE', true, false, 'open', 'US', 'US', false, true, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "Geen gebruik van gegenereerde code zonder review in veiligheidskritische toepassingen", "source": "GitHub Copilot Terms"}]'::jsonb),
('b1000000-0000-0000-0000-000000000007', 'grammarly-business', 'Grammarly (Business)', 'Grammarly', 'GPAI_TEXT', true, false, 'open', 'US', 'US', false, true, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "Teksten die door Grammarly worden verwerkt worden tijdelijk opgeslagen — controleer DPA op bewaarbeleid", "source": "Grammarly Privacy Policy"}]'::jsonb),
('b1000000-0000-0000-0000-000000000008', 'perplexity-pro', 'Perplexity AI (Pro)', 'Perplexity AI', 'GPAI_SEARCH', true, false, 'open', 'US', 'US', false, false, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "Geen DPA beschikbaar — niet geschikt voor verwerking van persoonsgegevens", "source": "Perplexity Privacy Policy"}, {"restriction": "Onderliggend model wisselt — model_control = none", "source": "Perplexity documentatie"}]'::jsonb),
('b1000000-0000-0000-0000-000000000009', 'otter-ai-business', 'Otter.ai (Business)', 'Otter.ai', 'GPAI_TRANSCRIPTION', false, false, 'open', 'US', 'US', false, true, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "Audio-opnames worden verwerkt op US-servers — DPA beschikbaar maar geen EU-opslag", "source": "Otter.ai Privacy Policy"}, {"restriction": "Deelnemers aan vergaderingen moeten op de hoogte zijn van opname (AVG + lokale wetgeving)", "source": "AVG art. 13/14"}]'::jsonb),
('b1000000-0000-0000-0000-000000000010', 'notion-ai', 'Notion AI', 'Notion Labs', 'GPAI_TEXT', true, false, 'open', 'US', 'US', false, true, '1.0', 'published', '2026-03-01', '[]'::jsonb, '[{"restriction": "AI-functies verwerken werkruimte-content via OpenAI API — content verlaat Notion-servers", "source": "Notion AI Privacy"}, {"restriction": "DPA beschikbaar — vereist Business/Enterprise plan", "source": "Notion DPA"}]'::jsonb)
ON CONFLICT (canonical_id) DO NOTHING;